# Generated by Django 2.0.6 on 2018-06-25 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('desc', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_excluded', models.BooleanField(default=False)),
                ('is_digital', models.BooleanField(default=False)),
                ('is_real', models.BooleanField(default=True)),
                ('is_playable_two_players', models.BooleanField(default=True)),
                ('total_plays', models.IntegerField(default=0)),
                ('total_rejects', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chooser.Game')),
            ],
        ),
    ]
