# Generated by Django 2.0.6 on 2018-06-25 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0003_auto_20180625_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='played_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
